defaults:
  -
    scope:
      type: "pages"
    values:
      category: main
  -
    scope:
      path: "_confs"
    values:
      layout: conf
  -
    scope:
      type: "posts"
    values:
      layout: post
      comments: true
      comments_locked: false
      hidden: false
  -
    scope:
      path: "web"
    values:
      category: web
  -
    scope:
      path: "_locales/**/web"
    values:
      category: web
  -
    scope:
      path: "citizen"
    values:
      category: citizen
  -
    scope:
      path: "_locales/**/citizen"
    values:
      category: citizen
  -
    scope:
      path: "dad"
    values:
      category: dad
  -
    scope:
      path: "_locales/**/dad"
    values:
      category: dad
  -
    scope:
      path:            "assets/**/*.pdf"
    values:
      sitemap:         false

# Exclusions
exclude:
  - ".csscomb.json"
  - ".ruby-version"
  - ".cache"
  - "node_modules"
  - "package.json"
  - "scripts"
  - "_tasks"
  - "_src"
  - "Gemfile"
  - "Gemfile.lock"
  - "gulpfile.js"
  - "LICENSE.md"
  - "netlify.toml"
  - "package-lock.json"
  - "README.md"
  - "Rakefile"
  - "tmp"
  - "vendor"
  - "staticman.yml"
  - "yarn.lock"
  - _posts/**/*.jpg
  - _posts/**/*.jpeg
  - _posts/**/*.png
  - _posts/**/*.gif
  - _posts/**/*.pdf
  - _posts/**/*.mp4
  - _posts/**/*.webm
  - _posts/**/*.ogv
  - borisschapira-dev.com+3.pem
  - borisschapira-dev.com+3-key.pem
include:
  - ".well-known"
  - ".htaccess"
  - ".htpasswd"
  - "_headers"
  - "_redirects"
  - "_locales"

# Site settings
name: 'Boris Schapira'
title: 'Boris Schapira'
email: borisschapira@gmail.com
description: "Blog personnel de Boris Schapira. Des avis sur les métiers du web mais aussi sur ma vie de parent et de citoyen."
url: "https://borisschapira.com"
baseurl: "/"
timezone: Europe/Paris
incremental: true
encoding: utf-8
lsi: true
repository: "borisschapira/borisschapira.com"

microtypo:
  median: true

# Author
name: 'Boris Schapira'
domain: 'borisschapira.com'
author:
  name: 'Boris Schapira'
  url: https://borisschapira.com/
  flickr: 'http://flickr.com/borisschapira'
  github: 'https://github.com/borisschapira'
  twitter: 'http://twitter.com/borisschapira'
  mastodon: https://framapiaf.org/@borisschapira
  twitter_username: '@borisschapira'
  gravatar: https://www.gravatar.com/avatar/e884b2ba7d66cfea7cb2185922c7a183
  linkedin: 'http://linkedin.com/in/borisschapira'
  feed: '/feed.xml'
  mailto: 'contact%40borisschapira.com'
  reading_speed_en: 478
  reading_speed_fr: 723

# Posts links and pagination
permalink: :year/:month/:title/

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  default_values:
    sitemap: false

# Collections
collections:
  confs:
    output: true

# Build settings
kramdown:
  hard_wrap: true

jekyll-archives:
  enabled:
    - "year"
    - "month"
  layouts:
    year: "archives"
    month: "archives"
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"

pwa:
  dest_js_directory: assets/js
  precache_recent_posts_num: 5
  precache_glob_patterns:
    - "assets/{scripts,fonts}/**/*.{html,js,css,,svg,woff2,jpg}"
    - index.html
    - web/index.html
    - citoyen/index.html
    - papa/index.html
    - web/index.html
    - en/index.html
    - en/web/index.html
    - en/dad/index.html

# Graphiques
mermaid:
  src: '/assets/scripts/vendors/mermaid.min.js'

# The average reading speed, in number of words by minute
reading_speed: 400

cloudinary:
  logo: avataar
  cloud_name: borisschapira
  presets:
    default:
      sizes: "(min-width:20em) and (max-width:50em) 20em, (min-width:50em) 30em"

dareboost:
  monitoring : …
  token: '…'

# Other parameters are defined through environment variables
algolia:
  application_id: 97EL687MDM
  index_name: jekyll
  api_key: 121a196f122a96cba48609ba6cee2839
  nodes_to_index: 'p,blockquote,li,div.paragraph'
  indexing_batch_size: 200
  settings:
    highlightPreTag: '<mark>'
    highlightPostTag: '</mark>'

compress_html:
  ignore:
    envs:
      - 'development'

localization:
  mode : manual
  locale : "fr"
  data_dir : locales # Sets the base location for *translation data*, within your *site's `data_dir`*.
  content_dir: _locales # Sets the base location for placing files to be re-rendered. Ignored in "auto mode".
  locales_set: ["fr","en"] # A list of locales the site will re-render files into